"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

from environ import Env

env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=["localhost",])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_yasg',
    'drf_spectacular',

    'task_app.apps.TaskAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'task_app.pagination.MyCustomCursorPagination',
    'PAGE_SIZE': 6,
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if not env.bool("USE_REMOTE_DB"):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": env.str("DB_NAME"),
            "USER": env.str("DB_USER"),
            "PASSWORD": env.str("DB_PASSWORD"),
            "HOST": env.str("DB_HOST"),
            "PORT": env.int("DB_PORT"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticatedOrReadOnly'],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'BLACKLIST_ENABLED': True,
    'AUTH_HEADER_TYPES': ('Bearer',),

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Tasks & SubTasks APP",
    "DESCRIPTION": (
        "Внутренняя документация к backend приложению.",
        "Доступ будет только у Staff команды. Работа через Session + JWT токены для API запросов."
    ),

    "VERSION": "1.0.0",
    "OAS_VERSION": "3.0.3",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVE_PUBLIC": False,
    "SERVE_PERMISSIONS": [
        "rest_framework.permissions.IsAdminUser",
    ],
    "SERVE_AUTHENTICATION": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "AUTHENTICATION_WHITELIST": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],

    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "displayOperationId": True,
        "persistAuthorization": True,
        "filter": True,
        "tryItOutEnabled": True,
        "docExpansion": "list",
        "defaultModelsExpandDepth": 2,
        "defaultModelExpandDepth": 2,
        "displayRequestDuration": True,
        "tagsSorter": "alpha",
        "operationsSorter": "alpha",
    },

    "SWAGGER_UI_OAUTH2_CONFIG": {},
    "REDOC_UI_SETTINGS": {},
    "SCHEMA_PATH_PREFIX": r"/api/v[0-9]+",
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": True,
    "SORT_OPERATION_PARAMETERS": True,

    "CONTACT": {
        "name": "Backend Team",
        "email": "backend@example.com",
    },
}



LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'simple': {  # Имя форматтера; потом будем ссылаться на него из handlers.
            'format': '[{levelname}] | {asctime}  --  {name}:  ({message})',  #
            'style': '{',  # Говорим logging, что шаблон написан в стиле str.format, а не через %.
        },
        "verbose": {  # Подробный форматтер.
            "format": "[{levelname}] {asctime} {name} | module={module} | func={funcName} | line={lineno:d} | pid={process:d} | tid={thread:d} | {message}",

            "style": "{",
        },
        "sql": {  # Отдельный форматтер для SQL.
            "format": "[{levelname}] {asctime} {name} | duration={duration} | sql={message}",
            "style": "{",
        },
    },

    'handlers': {  # Здесь описываем, куда физически отправлять лог-записи.
        'console': {  # Handler с именем console для вывода логов в stdout/stderr терминала.
            'class': 'logging.StreamHandler',  # Стандартный handler Python для вывода в консоль.
            'formatter': 'simple',  # Говорим handler'у использовать форматтер simple.
            'level': 'DEBUG'  # Этот handler будет принимать только INFO и выше.
        },
        "http_file": {
            "class": "logging.handlers.RotatingFileHandler",  # Файловый handler с ротацией по размеру.
            "filename": LOGS_DIR / "http_logs.log",  # Основной лог приложения.
            "maxBytes": 10 * 1024 * 1024,  # Ротация после 10 МБ.
            "backupCount": 10,  # Держим 10 архивных файлов.
            "formatter": "verbose",  # Пишем подробный формат.
            "level": "DEBUG",  # Сохраняем все уровни начиная с DEBUG.
            "encoding": "utf-8",  # Корректная кодировка файла.
        },
        "db_file": {  # Отдельный файл под SQL-логи.
            "class": "logging.handlers.RotatingFileHandler",  # Ротация по размеру.
            "filename": LOGS_DIR / "db_logs.log",  # Файл для SQL-запросов.
            "maxBytes": 20 * 1024 * 1024,  # SQL часто объёмный, поэтому лимит чуть выше.
            "backupCount": 5,  # Храним 5 предыдущих файлов SQL.
            "formatter": "sql",  # Специальный формат для SQL-записей.
            "level": "DEBUG",  # SQL в Django логируется на DEBUG уровне.
            "encoding": "utf-8",  # Корректная кодировка.
        },
    },

    'loggers': {
        "django": {  # Общие системные логи Django.
            "handlers": ["console"],  #
            "level": "INFO",  #
            "propagate": False,  # Без всплытия, чтобы не получить дубли.
        },
        "django.request": {  # Логи, связанные с HTTP-запросами
            "handlers": ["http_file"],  # Ошибки запросов дублируем в отдельный http_file-файл.
            "level": "DEBUG",
            "propagate": False,  # Не пускаем выше.
        },
        "django.db.backends": {  # Логгер SQL-запросов Django ORM.
            "handlers": ["db_file"],  # SQL пишем только в отдельный db_file.log.
            "level": "DEBUG" if DEBUG else "INFO",  # В debug-режиме собираем SQL детально, в prod обычно приглушаем.
            "propagate": False,  # Не смешиваем SQL с общими логами.
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
