# Generated by Django 6.0.3 on 2026-03-04 23:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='created_at', verbose_name='Task title')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Task description')),
                ('status', models.CharField(choices=[('10', 'New'), ('20', 'In Progress'), ('30', 'Pending'), ('40', 'Blocked'), ('50', 'Done')], default='0', max_length=20, verbose_name='Task status')),
                ('deadline', models.DateTimeField(verbose_name='Task deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Task created at')),
                ('categories', models.ManyToManyField(related_name='tasks', to='task_app.category', verbose_name='Task categories')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Subtask title')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Subtask description')),
                ('status', models.CharField(choices=[('10', 'New'), ('20', 'In Progress'), ('30', 'Pending'), ('40', 'Blocked'), ('50', 'Done')], default='0', max_length=20, verbose_name='Subtask status')),
                ('deadline', models.DateTimeField(verbose_name='Task deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Task created at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtasks', to='task_app.task')),
            ],
        ),
    ]
