# Generated by Django 6.0.3 on 2026-04-21 19:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subtask',
            name='unique_lower_title_subtask',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_lower_title_task',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('10', 'New'), ('20', 'In Progress'), ('30', 'Pending'), ('40', 'Blocked'), ('50', 'Done')], default='10', max_length=20, verbose_name='Subtask status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('10', 'New'), ('20', 'In Progress'), ('30', 'Pending'), ('40', 'Blocked'), ('50', 'Done')], default='10', max_length=20, verbose_name='Task status'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), django.db.models.functions.text.Lower('task'), name='unique_lower_title_subtask'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('deadline'), name='unique_lower_title_task'),
        ),
    ]
