# Generated by Django 6.0.3 on 2026-04-21 19:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_remove_subtask_unique_lower_title_subtask_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_lower_title_task',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('deadline'), name='unique_lower_title_deadline_task'),
        ),
    ]
