# Generated by Django 6.0.3 on 2026-04-29 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_category_deleted_at_category_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='owned_subtasks', to=settings.AUTH_USER_MODEL, verbose_name='Subtask owner'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='owned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Task owner'),
        ),
    ]
